Added "Oracle Linux Server" detection
CrowdStrike/falcon-linux-install-bash pull request #31
Opened 2021-12-16 17:50 UTC by Deej1976

Detected unknown OS "Oracle Linux Server", this allows the installation to proceeed.

2021-12-16 18:34 UTC, redhatrises commented
@Deej1976 thanks for opening this. Can you add the logic to handle "oracle linux server" to lines https://github.com/CrowdStrike/falcon-linux-install-bash/blob/main/falcon-linux-deploy.sh#L314-329 ?

2021-12-16 19:04 UTC, jshcodes approved these changes
Ack.

2021-12-16 19:17 UTC, redhatrises approved these changes

2021-12-16 19:19 UTC, redhatrises requested changes
Please move the code to https://github.com/CrowdStrike/falcon-linux-install-bash/blob/main/falcon-linux-deploy.sh#L301 so that we aren't duplicating handling different versions of a distribution.

2021-12-16 19:19 UTC, isimluk requested changes
The Oracle option already exists in the case statements.

The analysis is needed to determine why it is not picked up.

2021-12-17 09:43 UTC, Deej1976 commented
This is the output from puppet-console :

Fatal error: Unrecognized OS: Oracle Linux Server

From an Oracle Linux 8.5 Box:

[user@ol ~]$ export name=$(cat /etc/*release | grep ^NAME= | awk -F'=' '{ print $2 }' | sed "s/\"//g;s/Red Hat.*/RHEL/g;s/ Linux$//g;s/ GNU\/Linux$//g")
[user@ol ~]$ echo $name
Oracle Linux Server

[user@ol ~]$ cat /etc/*release
Oracle Linux Server release 8.5
NAME="Oracle Linux Server"
VERSION="8.5"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.5
Red Hat Enterprise Linux release 8.5 (Ootpa)
Oracle Linux Server release 8.5
[user@ol ~]$ cat /etc/*release | grep ^NAME
NAME="Oracle Linux Server"

And to compare against a Centos 7 box:

[user@centos ~]# export name=$(cat /etc/*release | grep ^NAME= | awk -F'=' '{ print $2 }' | sed "s/\"//g;s/Red Hat.*/RHEL/g;s/ Linux$//g;s/ GNU\/Linux$//g")
[user@centos ~]#  echo $name
CentOS

2021-12-17 10:47 UTC, isimluk commented
@Deej1976, I think I can close this PR as your alternative fix was merged in #32.

Thank You!

2021-12-17 10:47 UTC, closed without merging